### ISSUE TITLE
[Request] Text instead of numbers

### ISSUE THREAD

**Issue by pascaldulieu** [DrNewbie/RNGModifier#1]
Instead of numbers for the RNG locations could you add a general location for each item or computer so we would know where it would actually spawn as 1 or 5 is not clear at all.

**Comment by DrNewbie** [comment]
Feel free to improve it

**Comment by pascaldulieu** [comment]
I can give it a shot but i do not know a single thing about payday 2 modding or writing lua

**Comment by DrNewbie** [comment]
You don't need to know lua
