### ISSUE TITLE
Big Oil

### ISSUE THREAD

**Issue by KrogaFTW** [DrNewbie/RNGModifier#11]
The RNG options don't work at all.

Choosing an engine doesn't make it the right one and choosing what assets you get day 1 doesn't work either.

Either I don't understand how to use this or something is wrong.

**Comment by almog155** [comment]
1. picking an engine - as far as I can tell, choosing an engine does work. the engine number matches the label in the heist options.

2. day 1- I'm not 100% sure as I haven't tested it myself. It's possible it's one of the reoccurring bugs related to "connected" spawns (for example, if one table has the plane keys on it, other tables can't have these plane keys, therefore every index after plane keys is decreased by one for other tables). It basically means that the labels are somewhat wrong. The best solution I can give you around it for now is to simply ignore the labels for the tables and just try the combinations out yourself until you find something suitable for your needs.

**Comment by KrogaFTW** [comment]
Day One: I managed to get Scientist Intel on Floor 1, Keys on Floor 2, and Code on Balcony. I only tested it like twice, the other options seem to work.

Day Two: On normal, everything seemed to work fine, but on DSOD the only one that worked was the server room being ground floor. Selecting 8 in the menu didn't make engine 8 the correct one.

**Comment by KrogaFTW** [comment]
Engine 12 worked both times now, maybe a coincidence?

**Comment by almog155** [comment]
Day 1: I'd consider it solved then. A lot of heists act like that, sometimes you just need to ignore the labels.

Day 2: I just checked the world.xml file for day 2, didn't see anything related to the engine and difficulties. Are you sure your tests are 100% valid? (maybe you didn't restart the mission after changing the engine?)
If your tests are indeed valid, try to tell what label you put and what engine was correct, as I can't reproduce this myself.

**Comment by KrogaFTW** [comment]
Day One: Scientist Intel 1st Floor, Plane Key 2nd Floor, Shutter Code Balcony, No Coke Deal, Safe at Camera Guy, Boat Spawn all seemed to hold steady. I think I found a consistent set up for this day.

Day Two: Engine 12, In Woods pick up spot, 60s pick up time, Default plane location, First floor server room. The stars aligned and all of these seemed to work, the time between putting the bag in the helicopter and bain saying he received it was about 1 minute 30 seconds and not the 60 seconds I selected, though I'm not sure what is meant by pick up time. I'm pretty sure I got lucky on the Woods pick up spot because I've had it be at the pool even when Woods is selected. 

Engine 12 seems to work fine whenever I use it, I double check with the Cold Fusion Research though, just in case.

I still find it bizarre that no clipboards spawn anywhere in the house, I check a location guide and everything, if you don't have the cold fusion research, you have no way of knowing which engine is the right one, you have to purely go on faith the engine you picked is the right one.

I don't know if I would consider this solved by any means, It's pretty spotty and I would never try doing Engine Problem in a Crime Spree because of the lack of clipboards.

**Comment by KrogaFTW** [comment]
Disabling RNG Modifier returned the clipboards and PSI computer to the mission. Is there a reason why there are disabled in the first place?

Potentially unrelated, Day 2 stop being able to be completed entirely. All engines were the wrong ones. I don't know if this is RNG Modifier's fault or another mod conflicting with the mission.

**Comment by almog155** [comment]
well, as it turns out, not all 12 engines are possible to get. I have no idea how long this was in the game for or if it changes.
there are 9 possible engines, these are the right labels for them: (first number represents the engine label the RNGModifier, second number represents the ACTUAL engine number IN GAME)
1: 1,
2: 2,
3: 5,
4: 6,
5: 7,
6: 8,
7: 9,
8: 11, 
9: 12
picking any other label (10, 11, 12) should give the result of none of the engines are correct and no clipboards exist.

**Comment by KrogaFTW** [comment]
Yeah now that you mention it, every time I didn't have the research it didn't work. I'll try this later.

**Comment by KrogaFTW** [comment]
I did a quick test on normal, no research asset, and I set the engine to 9.

All the clues spawned in the basement, Engine 12 was correct, the mission was completed just fine.

So hopefully that's the end of that.
