### ISSUE TITLE
Force Escape option is overwritten every time the mod is loaded

### ISSUE THREAD

**Issue by m-alorda** [DrNewbie/RNGModifier#15]
I recently was trying to get all the escape achievements in the game. So, I wanted to force an escape on every day of every heist I was playing. However, the `Force Escape` option is reset every time the mod loads. This way, I had to go into `Options -> Mod Options -> RngManager -> All` and check the `Force Escape` option on EVERY preplanning screen of EVERY heist.

The code causing this issue is at `Base.lua:308`:
```lua
RNGModifier:SafeSetData(0, "all_of_all", "_forced_escape_day")
```

I would suggest not overwritting the value of this setting, so the code configuring the `Force Escape` option would now be:
```lua
-- Value not overwritten anymore
-- RNGModifier:SafeSetData(0, "all_of_all", "_forced_escape_day")
MenuCallbackHandler.RNGModifier_all_of_all_forced_escape_day = function(self, item)
	if tostring(item:value()) == "on" then
		RNGModifier:SafeSetData(1, "all_of_all", "_forced_escape_day")
	else
		RNGModifier:SafeSetData(0, "all_of_all", "_forced_escape_day")
	end
	RNGModifier:Save()
end
local _bool = tonumber(RNGModifier:SafeGetData("all_of_all", "_forced_escape_day")) == 1 and true or false
MenuHelper:AddToggle({
	id = "RNGModifier_all_of_all_forced_escape_day",
	title = "RNGModifier_all_of_all_forced_escape_day_title",
	desc = "RNGModifier_all_of_all_forced_escape_day_desc",
	callback = "RNGModifier_all_of_all_forced_escape_day",
	value = _bool,
	menu_id = RNGModifier._menu_All_id
})
_bool = nil
```

**Comment by DrNewbie** [comment]
https://github.com/DrNewbie/RNGModifier/commit/828db0f75b600656fbe4d9a853b8e830fc9cfff3
