### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by hbk314** [DrNewbie/RNGModifier#2]
Installed the new version. It no longer shows up under Mod Options in-game.

**Comment by hbk314** [comment]
Also causes a crash when attempting to start the new Diamond Heist.

**Comment by hbk314** [comment]
Still no change.

**Comment by DrNewbie** [comment]
working fine at my here

**Comment by hbk314** [comment]
Nope. Did something else change as far as the install?

I'm basically just replacing the RNGModifier folder in mod_overrides with the new one. It worked before, but now the options don't show up and the game crashes when trying to load a heist.

**Comment by DrNewbie** [comment]
https://github.com/DrNewbie/RNGModifier/commit/56f01eb35bc13177ca050591f940f5588d49e13e

sound like your issues, not codes problem

**Comment by hbk314** [comment]
It doesn't sound like that at all. If the install process hasn't changed, it's gotta be an issue with the code.

**Comment by DrNewbie** [comment]
solved. just some misunderstanding in installation
