### ISSUE TITLE
Still doesn't work.

### ISSUE THREAD

**Issue by hbk314** [DrNewbie/RNGModifier#3]
Why would you mark it solved when no solution has been found?

You didn't even answer my question. Did the install process change between two weeks ago and now?

**Comment by hbk314** [comment]
Hooks\menu\Menu Function.lua 

When I replace the old with the new, it no longer shows up in the Options.

**Comment by hbk314** [comment]
I updated every file but that one. Still shows up in the options, obviously without the new stuff in there, but the game doesn't crash.

Can you fix it from here?

**Comment by DrNewbie** [comment]
working fine at my here,
and sorry, you're not my boss

**Comment by DrNewbie** [comment]
PS:
Report ''It doesn't work'' is kind of useless when it is work fine at my here.
