### ISSUE TITLE
[Suggestion] Scarface Mansion: option to choose camera position in the start zone

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [DrNewbie/RNGModifier#33]
As the title says.
In the starting section of the heist, you meet 4 guards, often protected by a camera.
The camera does not always spawn on the same wall, at times it is even missing.
An option to choose between LEFT, RIGHT, TOP STAIRS and NO CAMERA would be a nice addition

Google translate to Chinese (hope it helps):
如标题所示。
在抢劫案的开始部分，您会遇到4个警卫，通常由摄像机保护。
摄像头并非总是在同一堵墙上产生，有时甚至会丢失。
在左，右，上楼梯和无相机之间选择的选项将是不错的选择

**Comment by Berk-Rider** [comment]
option added on update 14.5, but it only forces the cam to never spawn
