### ISSUE TITLE
issue with the new code in base.lua for multiple options in a single id

### ISSUE THREAD

**Issue by Berk-Rider** [DrNewbie/RNGModifier#84]
the new code forces all the "_A" options to always go back to default

example:
`if ED2_spawncrate_A ~= 0 and table.contains({ED2_spawncrate_B, ED2_spawncrate_C, ED2_spawncrate_D, ED2_spawncrate_E, ED2_spawncrate_F}, ED2_spawncrate_A) then`
no matter what you select ingame, ED2_spawncrate_A will always reset to default when the heist restarts

**Comment by Berk-Rider** [comment]
with the previous code all options were working just fine at least on my end
the only issue would be an option reseting back to default but after configuring it again the option would be saved

but with the new code on swing vote for example, the options for were the voting machine boxes will be are all single options to spawn at the right wing... and as far as I know you created these options, and now one of the boxes are always random because the option always reset back to default

**Comment by DrNewbie** [comment]
previous code would not run at all, so you wouldn't have noticed any issues.
I'm not talk about swing vote, what I mean is RNGModifier:Save() https://github.com/DrNewbie/RNGModifier/blob/3366d0d9d7efee8faee17f42df51c633cec35949/RNGModifier/Base.lua#L141
